name: fgm_hymn_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  logger: ^2.4.0
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fr_hymn.json
    - assets/en_hymn.json
